### ISSUE TITLE
java.lang.NullPointerException in EveritWorklog line 153

### ISSUE THREAD

**Issue by andre-c-andersen** [everit-org/jira-timetracker-plugin#162]
We are experiencing a 500 response with a null pointer exception when getting `http://jira/secure/JiraTimetrackerTableWebAction.jspa?dateFrom=2016-01-29&dateTo=2016-01-29&userPicker=andre.andersen` 

The following relevant trace was generated:

```
java.lang.NullPointerException
    at org.everit.jira.timetracker.plugin.dto.EveritWorklog.<init>(EveritWorklog.java:153)
    at org.everit.jira.timetracker.plugin.JiraTimetrackerPluginImpl.getWorklogs(JiraTimetrackerPluginImpl.java:783)
    at org.everit.jira.timetracker.plugin.JiraTimetrackerTableWebAction.doExecute(JiraTimetrackerTableWebAction.java:332) ...
```

It looks like `issueObject` in the constructor of `EveritWorklog` gets assigned `null` from the `issueManager` as described [here](https://docs.atlassian.com/jira/6.2.1/com/atlassian/jira/issue/IssueManager.html#getIssueObject%28java.lang.Long%29). It seems like there is an worklog entry without an issue. A quick fix could be to add exception handling in JiraTimetrackerPluginImpl which prevents orphan worklogs to show up. Something like:

```
for (GenericValue worklogGv : worklogGVList) {
    try {
        EveritWorklog worklog = new EveritWorklog(worklogGv);
        worklogs.add(worklog);
    } catch(java.lang.NullPointerException e) { /* log "e" or tell user */}
}
```

Or something else. I'll be getting access to the DB tomorrow so I can see if I can find the orphan worklogs and maybe delete or reassign them or something. Shouldn't break the app in any case.

**Comment by bordatesz** [comment]
Hi there!
We'll check it. Can you tell me which Timetracker and JIRA version you are using?

**Comment by andre-c-andersen** [comment]
Awesome! It first occurred using Timetracker 2.3.0, but upgraded to 2.3.1 in hopes that it would fix the issue. The JIRA version is 6.4.6 build 64021 on java 1.8.0_40 from Oracle. I hope that helps.

**Comment by bordatesz** [comment]
Thank you! We try to reproduce the problem.
I'll let you know as soon as we are done whit the fix.

**Comment by andre-c-andersen** [comment]
It might be connected to deletion of issues with work logged on it, or something similar. If that helps.

**Comment by bordatesz** [comment]
Hi there! We tried to reproduce this bug, but even if we deleted issue from the database, it's not occurs. However we expanded the exception handling in the actual 2.3.2-SNAPSHOT version. Please try it out, and let us know if the problem still occurs.

**Comment by andre-c-andersen** [comment]
2.3.2 isn't available in the market place. The error occurs for multiple users, not only me. Unfortunately this means we cannot use the tool. We will thus implement our own views using QlikView, or look for a different solution, and discontinue the everit timetracker. Thank you for your efforts with this open source project. We might try it again at a later time.

**Comment by bordatesz** [comment]
2.3.2 is a SNAPSHOT version, so it's not have been released. You can download it from the master branch, or if you provide me an email address, I can send you the compiled JAR file for test the fix. Because there there is not much bugfix in this scope, we don't plan marketplace release soon.

Please watch our plugin in the Marketplace to get notification for the next release, or (as I mentioned earlier) if you interested to try out our fix for you, provide me your email addres, so I can send it to you.
Thank you!
