### ISSUE TITLE
Bad conversion of the reported time if both start and end times are behond 12:00

### ISSUE THREAD

**Issue by diuus** [everit-org/jira-timetracker-plugin#169]
Hi,

I tried the development version.
If I introduce an interval 10:00 -> 15:00 everything is OK.
If I introduce an interval 14:00 -> 15:00 it converts it to 2:00 -> 3:00.

Best regards,
    Gil

**Comment by bordatesz** [comment]
Hi Gil!
You are right, this bug really exist. We'll look into it.
Thank you for the notification!

**Comment by bordatesz** [comment]
@diuus Fixed it in [this commit](https://github.com/daniel-toth-everit/jira-timetracker-plugin/commit/19c4767c41601e88b19f90f23900c75cce569768). Please let me know if further problems occur.
