### ISSUE TITLE
Jira base URL is not considered in worklog table entries

### ISSUE THREAD

**Issue by a-aristar** [everit-org/jira-timetracker-plugin#191]
Hi! 
In case base URL was changed for Jira instance, a link to an issue within worklog table displayed incorrectly - using default Jira settings, i.e. root context.
For example, Jira base URL is http://example.com/jira. In this case a link to and issue will look like http://example.com/jira/browse/ISSUE-1. But workloag table displays the link like http://example.com/browse/ISSUE-1.

TimeTracker version 2.3.5

**Comment by bordatesz** [comment]
Hi there!
Thank you for the notification. We left this out from the tables, but now it's fixed.
