### ISSUE TITLE
Start time is reset when there is no permission to log on issue

### ISSUE THREAD

**Issue by balazs-zsoldos** [everit-org/jira-timetracker-plugin#272]
Reproduce:
- I set the start time and end time of the log (or duration)
- I try to save the worklog but I do not have permission to log onto an issue
- The start time is different than the original (and probably duration is lost, too)

**Comment by bordatesz** [comment]
We'll look into it!

**Comment by bordatesz** [comment]
Fixed in the latest release: [3.2.0](https://github.com/everit-org/jira-timetracker-plugin/releases/tag/v3.2.0), [2.6.0](https://github.com/everit-org/jira-timetracker-plugin/releases/tag/v2.6.0)
