### ISSUE TITLE
Invalid Start Time on Reporting

### ISSUE THREAD

**Issue by fortax** [everit-org/jira-timetracker-plugin#312]
I'm unable to create a Report. When I click "Create Report" it appears the error message "Invalid Start Time". Any Tips?

![timetracker](https://cloud.githubusercontent.com/assets/1496766/17429485/1137d5f0-5aef-11e6-97ef-5edbbe6017e3.jpg)

**Comment by daniel-toth-everit** [comment]
Hi there!

Thank you for your report! We are aware of the issue and actively working on a solution. We are doing our bests to fix this in our next release.

Until then, you can use the following work around. Change your date separator from dot to something else, for example to slash. You can do this at the "Look and Feel" Administration page by modifying the Day/Month/Year Format parameter value..

**Comment by bemace** [comment]
We're also seeing problems respecting our date format settings. In our case, it insists on having leading zeros for the day and month regardless of our settings.

**Comment by bordatesz** [comment]
Hi there!
I apologize for the late update. We are working on this, but because of other tasks, we were not able to finish and publish the bugfix release. Now I can say that the fix will be released within a week or two.
Thank you for your patience.

**Comment by bordatesz** [comment]
Hi there!
Sorry for the late update. This is fixed in the latest release: [3.2.0](https://github.com/everit-org/jira-timetracker-plugin/releases/tag/v3.2.0), [2.6.0](https://github.com/everit-org/jira-timetracker-plugin/releases/tag/v2.6.0)
