### ISSUE TITLE
Idea - Issue name

### ISSUE THREAD

**Issue by pchovanak** [everit-org/jira-timetracker-plugin#382]
We would like to have possibillity to see whole name of the issue in the column "Issue". The key of the issue is useless for us.

Thanks

**Comment by bordatesz** [comment]
Hi there,
Thank you for your feedback. Do you want this improvement for the Timetracker screen?

**Comment by pchovanak** [comment]
Yes, for the Timetracker screen.
Thanks

**Comment by balazs-zsoldos** [comment]
Very old versions of timetracker contained the issue subject in each line. However, long subjects made it hard to read the data in the table. Therefore it is accessible via the tooltip at the moment (if you move your mouse over the issue id).

@bordatesz We could probably show a truncated part of the subject based on user preferences.

**Comment by pchovanak** [comment]
It is still better to see at least half of the issue name than issue key. We know about the tooltip, but it is not comfortable when you have 10 issues during the day and when you need the glimpse of what you already logged.

**Comment by bordatesz** [comment]
As Balázs said, this is a design matter. 
We will investigate how we can properly display the Issue summary on the screen, but I would like to ask for your patience because we just released the Timetracker with the new design last week, and we want to collect feedbacks about it first.

**Comment by pchovanak** [comment]
Thanks, we will wait.

One more comment - my colleagues would like to have option to show (pernamently) the calendar as it was in the older version. Considere it just as comment. I can imagine that from the designer (GUI/UX) point of view it could be not so good idea.

Regards

**Comment by bordatesz** [comment]
Thank you, and all feedback/comment is welcome! We have an idea for the permanent calendar too if it will be requested by more users. I'll notify you here if we decide to develop it.

**Comment by bordatesz** [comment]
Hello @pchovanak 
We added a feature, which you can choose whether you want to display the Issue Summary or the Issue Key on the Timetracker screen. The new version will include this, which will be released within a week.

**Comment by pchovanak** [comment]
Thanks @bordatesz. Looking forward to it!

**Comment by bordatesz** [comment]
Hello @pchovanak ,
We released the new version which includes this selectable Issue Key/Summary column option in Timetracker. Let me know how you like it.
