### ISSUE TITLE
Not correct date after click on today button and switch 

### ISSUE THREAD

**Issue by konstantinkosev** [everit-org/jira-timetracker-plugin#403]
Hello,

I am facing the following issue (frankly, it's not a big deal, but somehow is annoying):
From timetracker I click today button, then click a button to change the day to the previous or next one. In case I select previous day, it pulls me two days before today. In case I select 'tomorrow' it is showing the current day. 

Would you please check what is going wrong here? 

Not a browser issue, as mine colleagues have the same behavior of the system...

Many thanks,
![todaybutton](https://cloud.githubusercontent.com/assets/22954803/19553707/f877a2a6-96bd-11e6-9122-f473da1de1dc.PNG)

**Comment by bordatesz** [comment]
Hello there,
Can I ask you what version do you use? 
This is possibly related to the TimeZone problem we fixed in the latest [release](https://marketplace.atlassian.com/plugins/org.everit.jira.timetracker.plugin/server/versionhistory).

**Comment by konstantinkosev** [comment]
Hi Bordatesz,

Thanks for the prompt reply. The version is 3.2.1. 
Can you try is the same happens in your system? 

Best regards,

**Comment by bordatesz** [comment]
@konstantinkosev 
We can't reproduce this behavior. We suspect that the cause is wrong server time on your side.  To confirm this, please open the Log Work dialog from Issue screen and check if the DateTime is correct for today.
![image](https://cloud.githubusercontent.com/assets/5459077/19557618/eae743ea-96c6-11e6-8941-83899cd1b453.png)

**Comment by bordatesz** [comment]
@konstantinkosev 
Did you able to check the default Log Work date? If that is correct, but the Timetracker is still behaving incorrectly, we will investigate further.

**Comment by konstantinkosev** [comment]
@bordatesz Thanks for the proactive handling of the problem.
At the moment we had an outage so it is not possible to check. Most likely the time/date settings of the Jira srv are correct. Also the date time settings via the Jira interface was correct when I opened last time.
Any idea what else can affect the behavior? Also if there is misalignment for time/date settings they should be with one day, with most likely is not the case...

Many thanks!

**Comment by bordatesz** [comment]
@konstantinkosev 
To reproduce the problem, I would like to ask a few questions:
- What is the date and time on your JIRA server?
- What language is used in your JIRA?
- What Timezone is set in your [profile](https://confluence.atlassian.com/jira064/choosing-a-time-zone-720416101.html)?
- What date and time format have been set in the [Advanced settings](https://confluence.atlassian.com/adminjiraserver071/configuring-advanced-settings-802593105.html) for pickers?
- What date and time format have been set in the [Look and Feel settings](https://confluence.atlassian.com/adminjiraserver071/configuring-the-look-and-feel-of-your-jira-applications-802592278.html)?

**Comment by konstantinkosev** [comment]
@bordatesz 

1st one - you mean server OS ?
2 - English. 
3 - In my profile GMT +2, other users with other timezone set in their profile have the issue too.
4 and 5 - attached screenshots.
![pasted image at 2016_10_25 14_10 1](https://cloud.githubusercontent.com/assets/22954803/19718617/bdad442c-9b6e-11e6-8d55-27d18299079d.png)
![pasted image at 2016_10_25 14_10](https://cloud.githubusercontent.com/assets/22954803/19718616/bdad22e4-9b6e-11e6-98b1-87eb1df10532.png)

**Comment by bordatesz** [comment]
@konstantinkosev 
- Yes, I mean the servers OS system time. That is a very important piece of info for us.
- Did you able to check the DateTime field on the default Log Work screen?
  Thank you for the rest of the information.

**Comment by konstantinkosev** [comment]
Hi @bordatesz 

We found out that we have a bit miss-configured OS D/T settings. When we apply the change will let you know is that help solve us the issue.

Again, many thanks for the efforts here.

**Comment by bordatesz** [comment]
Hi @konstantinkosev 
Thank you, let me know the result of the configuration change.
In the meantime, we continue to the investigation of this issue.

**Comment by bordatesz** [comment]
@konstantinkosev 
Hello there! Did the re-configuration solve this Issue?

**Comment by konstantinkosev** [comment]
Hi @bordatesz,

For regrets it does not work as it should. The linux settings are from Jira srv, the win one - from DB.

Also to be clear - did you try to click Today just before trying to move one day in the past?

Best regards,
Kosta

<img width="474" alt="screen shot 2016-11-02 at 11 01 47" src="https://cloud.githubusercontent.com/assets/22954803/19924561/1eea4600-a0f5-11e6-9e95-9a5d261ed639.png">
<img width="673" alt="screen shot 2016-11-02 at 11 03 05" src="https://cloud.githubusercontent.com/assets/22954803/19924560/1ee7ec84-a0f5-11e6-8c69-6cf60ffee580.png">

**Comment by bordatesz** [comment]
Hi @konstantinkosev 
We identified the cause of this problem and working on the fix. At present, the Timetracker takes into account only the server time, regardless of time zone, and there is a date parse bug too.

There are two ways to handle worklog datetimes:
- "JIRA treats all date/time fields as absolute points in time stored as UTC and converted to and from the user's timezone during input or output. " We currently choose to go with this. This way, we will be consistent with the JIRA, but in case of users worked time from different timezones the Timetracker reports will show misleading information.
- The other way is to save datetime to server always with the user timezone, and not converting the user input to server time. This way, the Timetracker reports will always show the right time for user worklogs, but the JIRA will apply the timezone and datetimes in any JIRA srcreen will be misleading.

Which way would be the better option for you?

**Comment by konstantinkosev** [comment]
@bordatesz 

Yes, option one makes more sense from my PoV too.

Cheers,

**Comment by bordatesz** [comment]
Hello @konstantinkosev 
We added Time Zone support to the latest Timetracker versions. Please try it out and let me know if it's solved this issue.

**Comment by bordatesz** [comment]
Hello @konstantinkosev 
Sorry for the delay with this issue. We just released the fix for this error. Please upgrade Timetracker and let me know if it solved your issue.

**Comment by konstantinkosev** [comment]
@bordatesz 

Yes, the issue with the latest version is solved. Confirmed. 
This thread is not needed any more. 

Thank you for the efforts spent here. Great job!
