### ISSUE TITLE
Ability to track time without issue

### ISSUE THREAD

**Issue by rylach** [everit-org/jira-timetracker-plugin#409]
Many time trackers enable to track time without specifying exact task a'priori (but they cannot export time directly to Jira  ).
It would be nice to do the same on ictimeTimeTracking. It would be very helpful to be able to fast start timer with some label/keyword and at the and of day distribute it to different issues.

**Comment by balazs-zsoldos** [comment]
Hi @rylach,

what about creating a dummy issue for that (probably in a dummy project)? E.g.: DUMMY-1. By doing that, DUMMY-1 worklogs can be part of any reports in Jira.

We use issues for holidays and non-working activities, too and we found it very helpful.

Regards,
Balazs

**Comment by bordatesz** [comment]
@rylach 
Hi there! Didn't you accidentally mix us with the ictime add-on? :) 
If not: We are already considering the automatic time tracking feature, but we did not plan to implement it in the near future. Can I ask you, how important is this feature for you?

**Comment by rylach** [comment]
We'are considering both of you ;-)
We really seek for one time tracker for all. Some of us (in our company) are using hamster (automatic tracking, but has to be patched to export to Jira, and harder to use on Windows desktops). It seems to be the best solution for linux users. 
Others are using Tempo tracker - automatic tracking, but inconvenient/hard editing of already tracked time.
I think, that the best usage pattern for many is:
1. Track time switching fast between any being-fast-to-locate-issue or your-own-label-identifying-issue-or-type-of-work
2. At the end of day distribute the time between issues.

I've been using Hamster just like this for many years, it was ok even without issue tracker integration.

Combining these two in one tool in my opinion would be a killing feature.

Best regards,
Ryszard.

**Comment by bordatesz** [comment]
Hello @rylach 
Thank you for considering us too and we are very happy about it. :)
We can offer our easy to use interface where worklog can be added or edited.

The automatic time tracking solution with labels will be indeed a powerful feature and I added it to our backlog, but unfortunately it will be developed at some time in the future, maybe in the next year. 
In the meantime, whether if your choice falls on us or not, feel free to contact me with any questions or  feature request!

**Comment by rylach** [comment]
Thank you for you reply. Meantime, maybe we'll be able to find some developer to contribute...

Best Regards,
Ryszard.

**Comment by bordatesz** [comment]
@rylach 
Indeed, therefore I leave this Issue in open state.
Regards,
Attila

**Comment by bordatesz** [comment]
This issue is closed due to a lack of contribution. We will implement the auto logging in the future.
