### ISSUE TITLE
Worklog edit is broken

### ISSUE THREAD

**Issue by a-aristar** [everit-org/jira-timetracker-plugin#424]
It looks like 3.3.0 and 3.3.1 versions have significant problem.
I can't edit existing worklog entry.
If I click edit entry followed by Now button, End Time contains string: "TU.10.YYYY 21:35"
If I switch to Duration field (entering, say, 00:02) and try to save entry, I hit an error:
Invalid Start Time! (and nothing in atlassian-jira.log)

BTW, Start time field contains 15.11.2016 17:23

If I leave only 17:23 and try to save the entry, I hit Error 500.
And atlassian-jira.log contains
java.lang.RuntimeException: javax.servlet.ServletException: java.lang.IllegalArgumentException: Invalid format: "14:01" is malformed at ":01"

Our instance is Jira 7.1.4
System Encoding	UTF-8
jira.date.picker.java.format	d/MMM/yy
jira.date.picker.javascript.format	%e/%b/%y
jira.date.time.picker.java.format	dd/MMM/yy H:mm
jira.date.time.picker.javascript.format	%e/%b/%y %H:%M
jira.date.time.picker.use.iso8061	true
jira.i18n.default.locale	ru_RU
jira.lf.date.complete	dd.MM.yyyy HH:mm
jira.lf.date.day	EEEE HH:mm
jira.lf.date.dmy	dd/MM/yyyy
jira.lf.date.relativize	false
jira.lf.date.time	dd.MM.yyyy HH:mm

**Comment by bordatesz** [comment]
Hello @a-aristar ,
It seems you have a misconfiguration. The name is misleading, but the jira.lf.date.time should only contains the time format (see [here](https://jira.atlassian.com/secure/attachment/14498/jira-application.properties)). In your case: jira.lf.date.time = HH:mm

The following properties are the equivalent of the [Look and Feel](https://confluence.atlassian.com/adminjiraserver071/configuring-the-look-and-feel-of-your-jira-applications-802592278.html) date and time formats:

Properties:
jira.lf.date.time = hh:mm a
jira.lf.date.day = EEEE hh:mm a
jira.lf.date.complete = dd/MMM/yy hh:mm a
jira.lf.date.dmy = dd/MMM/yy

Settings:
![image](https://cloud.githubusercontent.com/assets/5459077/20342048/1b2a673a-abe9-11e6-9913-0265268ae30e.png)

**Comment by a-aristar** [comment]
Thanks. Now it works fine.
