### ISSUE TITLE
some durations in format hh:mm block creation/update of worklog (on 3.3.2)

### ISSUE THREAD

**Issue by javathought** [everit-org/jira-timetracker-plugin#440]
I'm not able to input 02:00 04:00 or 08:00 as a duration  (error: "Unsuccessful worklog update.")
but I can type 4h or 4:30. 

It's seems to occurs on even hours (full).

**Comment by bordatesz** [comment]
Hello @javathought 
We will investigate this issue. Thank you for your feedback.

**Comment by bordatesz** [comment]
Hi @javathought 
Unfortunately, we didn't able to reproduce the problem. With the same version, we didn't dedect any irregularity. 
Can you attach some screenshots or logs?
