### ISSUE TITLE
RFE: API

### ISSUE THREAD

**Issue by jrogers512** [everit-org/jira-timetracker-plugin#445]
It'd be great to have an API for this plugin, that would allow me to log work (or get reports of logged work) from other applications and/or command line tools.

**Comment by bordatesz** [comment]
Hi @jrogers512 
We are not planning to extend Timetracker with any kind of API, but please check out our [Worklog Query](https://marketplace.atlassian.com/plugins/org.everit.jira.worklog.query.plugin.core/server/overview) plugin, with which you can query worklogs through REST API. 
For adding worklog, you can use the default JIRA REST API, what you can [see here](https://docs.atlassian.com/jira/REST/server/#api/2/issue-addWorklog).
