### ISSUE TITLE
When adding worklog for current date, it saves it for previous date.

### ISSUE THREAD

**Issue by MaSergiu** [everit-org/jira-timetracker-plugin#459]
Hello.
First of all let me thank you for your work on this plugin.
Here's what problem I'm facing:
 - before pressing "Save" button - http://pix.toile-libre.org/upload/original/1483437321.png
 - after pressing "Save" button - http://pix.toile-libre.org/upload/original/1483437360.png
Good luck.

**Comment by bordatesz** [comment]
Hello @MaSergiu 
Thank you for the feedback!
Can you show me the following settings?
- Do you use User profile or System TimeZone settings in the Timetracker?
- What is your current user profile time zone? Is there any difference between your location's timezone (eg. in your os, or browser) and what is selected in your profile?
- What is your system (server) timezone?

**Comment by MaSergiu** [comment]
Hi @bordatesz 
I'm pleasantly surprised with your fast answering process. 

I hope the following screen-shots will answer to your questions:
1. http://pix.toile-libre.org/upload/original/1483438910.png - it's System setting
2. http://pix.toile-libre.org/upload/original/1483439006.png - there is a difference of 1 hour
3. http://pix.toile-libre.org/upload/original/1483438965.png - the same hour.

Thank you for your support!

**Comment by bordatesz** [comment]
Hi @MaSergiu 
We are trying to reproduce the problem, but this is a very mysterious bug, so if you don't mind, I have more questions.
- Can you provide me some additional information about your DateTime settings in JIRA's Advanced and Look and Feel settings?
- Is there a reason why do you use 12-hour format?
- Isn't your clock one hour ahead? (Based on your Ubuntu screenshot. We are in the same Timezone, but here it is before noon.)

**Comment by MaSergiu** [comment]
Hello @bordatesz 
Here are the answers for your last request:
1. http://pix.toile-libre.org/upload/original/1483443439.png - Look and feel settings;
2. This format was installed by the server administrator of Jira;
3. You're right. Jira users are in UTC+2.00 (Bulgaria, Cyprus, Estonia, Finland, Greece, Israel, Latvia, Lebanon, Lithuania, Moldova, Northern Cyprus, Palestine, Romania, Syria, Ukraine). So the difference between server and users is 1 hour. 

My time on this answer is 13:45.

**Comment by MaSergiu** [comment]
I don't know if it helps, but here are other observations:
http://pix.toile-libre.org/upload/original/1483451442.png
Case 1. Being on Tracker's screen at the current date press the "Previous date" button.
    Result ---> It doesn't show the previous date (expected 02/Jan/17), but one day earlier 1/Jan/17;
Case 2. Being on Tracker's screen at the current date press the "Next date" button.
    Result ---> It doesn't show the next date (expected 04/Jan/17), but it stays on the same date 3/Jan/17. And if you press it again, only then it shows 4/Jan/17.

**Comment by bordatesz** [comment]
Hi @MaSergiu 
Thank you again! We identified the problem and already working on it and I'll notify you as soon as we released the fix.

**Comment by bordatesz** [comment]
Hello @MaSergiu 
We just released the fix for this error. Please upgrade Timetracker and let me know if it solved your issue.

**Comment by MaSergiu** [comment]
Hello.
Thank you for your job.
My problems are solved.
Good luck in further development.

**Comment by bordatesz** [comment]
Thank you!
