### ISSUE TITLE
Add "Parent_Issue_key" and "Parent_Issue_Description" columns to Reporting page drilldown

### ISSUE THREAD

**Issue by praveen6300** [everit-org/jira-timetracker-plugin#462]
Hi,

My request is to add Parent issue_key and Parent Issue_description in drilldown of Time Tracker->Reporting.

Please find attached screenshot.

Regards,
Praveen Kumar C
![report_drilldown](https://cloud.githubusercontent.com/assets/12622212/21977134/edcf11b8-dbfa-11e6-941d-37ea3e6a36a5.png)

**Comment by bordatesz** [comment]
Hello @praveen6300 
Thank you for your request. We will consider it in the future.

**Comment by gitemconte** [comment]
I agree, this would be a very useful feature for teams that log time on sub-tasks only.

I actually came here to add an enhancement request to add a 'GROUB BY' feature in the reporting, so I can group all sub-tasks by their parent story, however, I think just having these columns and being able to sort on them would be exactly enough.

**Comment by bordatesz** [comment]
Hello there,
I'm happy to tell you, that "Parent Issue" and "Sub tasks" columns will be available in the next version.
