### ISSUE TITLE
Reporting - Quick Summary, add Organisation and Customer

### ISSUE THREAD

**Issue by nstayte** [everit-org/jira-timetracker-plugin#472]
Under the reporting option it would be nice to have the quick summary show the time logged against a customer or organisation.

**Comment by bordatesz** [comment]
Hello @nstayte 
Thank you for your feedback!

How do you identify your customers/organizations in your JIRA? Do you use custom fields for this purpose?

**Comment by nstayte** [comment]
Hi @bordatesz, thanks for your hard-work. We are using Jira Service Desk. The reporter is the customer and the customer can belong to an Organisation. Organisations are a recent addition to the Jira Service Desk. 

Link to organistaions https://confluence.atlassian.com/servicedeskcloud/blog/2016/09/group-customers-in-organizations

**Comment by bordatesz** [comment]
Hello @nstayte 
Thank you! We were not aware of this, but in the future, we will definitely look into this. :)

**Comment by bordatesz** [comment]
In the future, we will improve the support for Service Desk. We will be able to provide solutions for the organization field after solving the problem with custom fields.
