### ISSUE TITLE
Notification email

### ISSUE THREAD

**Issue by FannyMendez-Valiantys** [everit-org/jira-timetracker-plugin#493]
Hello,

I've found the following page on your documentation : (https://confluence.everit.biz/display/TD/Notification+email)
Is there any way to disable those notifications at all ? I didn't found this settings anywhere.

Thank you !
Regards,
Fanny

**Comment by bordatesz** [comment]
Hello @FannyMendez-Valiantys 
Choose JIRA-Administration > Add-ons. > Locate TIMETRACKER section > Open Global Settings page:
In the older versions, put the following expression in the input field: .*
In the newer version, simply select "None" option, to disable the notification emails.

**Comment by FannyMendez-Valiantys** [comment]
Thank you very much @bordatesz :+1: :)
