### ISSUE TITLE
Adding JIRA Custom Fields to Reports

### ISSUE THREAD

**Issue by pieViks** [everit-org/jira-timetracker-plugin#502]
Is it possible to add JIRA's custom fields to reports?

**Comment by bordatesz** [comment]
Developing a solution to add custom fields to reporting is a highly requested and long-planned improvement, but unfortunately, it's quite a difficult task with the development framework. In short: The flexibility of JIRA, which provides convenience when adding custom fields, makes the query of the fields difficult for us.
We're trying to find a solution without a large performance loss. I hope we can at least release a version with the improved export function in this summer.
