### ISSUE TITLE
Time of Logging

### ISSUE THREAD

**Issue by pieViks** [everit-org/jira-timetracker-plugin#503]
I've set Timetracker to use System Timezone. 

**Case # 1**
My JIRA configuration and time-zone settings are as follows:
Default user time zone:	Region = System Default, Time Zone = (GMT+01:00) Rome
User Local Time Zone is: UTC + 5:30
User JIRA Preferences (Profile Settings) Time Zone is: (GMT+01:00) Rome

While I log the work using JIRA Log Work, the recorded time is 5:53 AM (correct one) whereas Timetracker records the very same time entry at 1:53 PM (incorrect one).

I attach the screenshot where the first entry was logged using JIRA Log Work functionality and second entry was logged using TimeTracker Add Work Log.

<img width="352" alt="screen shot 2017-04-01 at 9 44 33 am" src="https://cloud.githubusercontent.com/assets/10341091/24575337/9e3ea8c4-16c0-11e7-8e32-b40943229be7.png">

**Case # 2**
My JIRA configuration and time-zone settings are as follows:
Default user time zone:	Region = System Default, Time Zone = (GMT+01:00) Rome
User Local Time Zone is: (GMT+01:00) Rome
User JIRA Preferences (Profile Settings) Time Zone is: (GMT+01:00) Rome

While I log the work using JIRA Log Work, the recorded time is 11:33 AM (correct one) whereas Timetracker records the very same time entry at 01:33 PM (incorrect one).

**Comment by bordatesz** [comment]
What Timetracker version do you use?
 
By default, the plugin uses the system time zone (the configured server timezone on which the JIRA instance is running) to show and to store dates. 
By using the "User profile setting" the dates and times will be shown in the user's time zone throughout the plugin. Timetracker does not deal with the local timezone.
If the user's profile settings differ from the system time zone then dates may differ, because the date storage in the system still will be based on the system time zone.

In your case, I suggest you configure Timetracker to "User profile setting" and configure the timezone in your profile as your local timezone.

**Comment by pieViks** [comment]
I'm using version 3.4.4.

I've read the same explanation in the user guide but there seems to be an issue with the time of recording. I'll do some more test next week.

We've a distributed team with team members working in different time-zones so it could be all very tricky. Need to perform few different tests.

Thanks for your response.

**Comment by bordatesz** [comment]
Timezone is always a hard thing in distributed teams I think. We provide two solution:
1. Using system timezone: In this case, everybody is on the same page, and see exactly the same dates and times IF everybody using Timetracker. (JIRA will add timezone on it's pages.)
2. Using user timezone: In this case, each user will see the datetimes in his configured timezone, but there will be difference in some cases..

JIRA and Timetracker always convert the date and time you enter to your server TZ before saving it to the database. JIRA and Timetracker (using user setting) converts the worklog dates back to the user timezone only when displaying, searching, etc.

**Comment by bordatesz** [comment]
Hello @pieViks 
Any progress with the testing?

**Comment by pieViks** [comment]
I've gone ahead with the System TimeZone. Still observing the results to evaluate the behaviour.
By the way, one of the feature we would like to have it is override the AM/PM clock with 24 hours clock. It seems a JIRA setting but is it possible to have a plugin settings to override it as well?

**Comment by bordatesz** [comment]
Unfortunately, it's not possible. Timetracker uses the JIRA date and time settings to display them, and this way it's consistent with what users see in JIRA (eg. on issue pages). 
If we receive more requests for this functionality, we'll certainly consider the implementation in the future.

If you want to use 24-hour format, you should use the following Look and Feel configuration:
- Time Format: HH:mm
- Day Format: EEEE HH:mm
- Complete Date/Time Format: dd.MMM.yy HH:mm
- Day/Month/Year Format: dd.MMM.yy

But in this case, the times will be displayed everywhere in JIRA in 24-hour format.

**Comment by pieViks** [comment]
Thank you for your response. Yes I'm aware of the fact that the setting will change the format throughout JIRA..Thanks again!
