### ISSUE TITLE
Show summaries in hours (in tooltip)

### ISSUE THREAD

**Issue by glen-84** [everit-org/jira-timetracker-plugin#504]
For summaries like this:

> Monthly Summary |	Work: 4w 1d 2h 5m

Could you please show the total number of hours (e.g. `170.0833`) – maybe in a tooltip?

Thanks.

**Comment by bordatesz** [comment]
Hello there,
This is already implemented and possible in the latest versions of Timetracker. (After the new design, so version 2.6.0 and 3.2.0)

**Comment by glen-84** [comment]
I didn't really want to change the general/default time format, I was just suggesting this as an additional feature.

**Comment by bordatesz** [comment]
@glen-84 
In this case, I have good news for you. This will be available in the next version as a user option. :) You will be able to display times in hours as a decimal number.

**Comment by glen-84** [comment]
Awesome, thanks Attila.
