### ISSUE TITLE
Broken date selector in Create Issue window

### ISSUE THREAD

**Issue by SharXeniX** [everit-org/jira-timetracker-plugin#505]
if you try to create an issue while the time tracker page is open (click on Create on top of the page)
the due date calendar dont show up when you click the calendar icon.

The calendar popup is created under the create issue windows.
Seems to be z-index related.

**Comment by bordatesz** [comment]
Hello @SharXeniX 
Thank you! This is a big deal, and we will fix it as soon as possible.

**Comment by bordatesz** [comment]
This will be fixed on all Timetracker pages in the next version.
