### ISSUE TITLE
Time registration fails due to "Invalid End Time"

### ISSUE THREAD

**Issue by Magnus1990P** [everit-org/jira-timetracker-plugin#506]
Registration of work fails due to invalid times being inserted, even though they appear to be correct.
Time zone is set to "system settings" server and Europe/Oslo.

The issue appeared after upgrading to 3.4.4 for Jira Server 7.0.10. And an example of the issue is provided below. Sometimes the reloaded page appends a space at the end of the time values also.

![capture](https://cloud.githubusercontent.com/assets/3428654/24801001/bb66508c-1ba2-11e7-971f-dc425face6c4.PNG)

**Comment by bordatesz** [comment]
Hello @Magnus1990P 
This error is probably caused by your Look and Feel time configuration.
Please review your Look and Feel settings and search for unnecessary space character in the time input field.

**Comment by Magnus1990P** [comment]
That solved the problem.
Thanks for prompt reply, @bordatesz .
