### ISSUE TITLE
Worklog entry is deleted if assigned to a non-accessible issue during editing

### ISSUE THREAD

**Issue by erosb** [everit-org/jira-timetracker-plugin#54]
Hello,

I found that the timetracker deletes a worklog entry if I try to re-assign it to an issue I don't have access to

Steps to reproduce
------------------------
- click the "edit" button of a worklog entry
- change the issue to an other issue you don't have access to (something that yields "Permission Violation" if you want to open it)
- click the "save" button

Actual behaviour
---------------------
the worklog entry is deleted

Expected behaviour
-------------------------
the worklog entry should not be deleted but should be kept unmodified (it should belong to the original issue), and a reasonable error message should be provided

**Comment by balazs-zsoldos** [comment]
It was a security problem. The worklog was moved to other project as there was write permission on it, but than the worklog could not have been read as there was no read permission on the other project.
