### ISSUE TITLE
Labels missing for unsupported languages

### ISSUE THREAD

**Issue by czsefira** [everit-org/jira-timetracker-plugin#79]
If I switch JIRA to a language not supported by TimeTracker (1.4.1), e.g. Czech, the label name is displayed for page components rather than a default English text. For example, the Submit button will display "plugin.submit" instead of "Submit".

**Comment by bordatesz** [comment]
Thank you for the notification. This problem will be fixed in the next release. Please, keep an eye on it.

**Comment by bordatesz** [comment]
Fixed in version 1.4.3
You can download it from the [marketplace](https://marketplace.atlassian.com/plugins/org.everit.jira.timetracker.plugin/versions).
